### ISSUE TITLE
daily task

### ISSUE THREAD

**Issue by psykkis** [Alt-Org/Altzone#109]
[Dailytask Jatko ohjeistus.pdf](https://github.com/user-attachments/files/18212301/Dailytask.Jatko.ohjeistus.pdf)

Daily taskissa on 3 välilehtikokonaisuutta:

1. avoimet tehtävät
2. oma työskentelyikkuna
3. listaus klaanin jäsenistä joilla on tehtävät kesken

[DAILY TASK & SERVERI](https://docs.google.com/document/d/1Axz1F07mkkBNHkhVvBi1GRjwIQcqpTIfT1Ow4gTiFLQ/edit )

[LISTA TEHTÄVISTÄ](https://docs.google.com/spreadsheets/d/13NA6G8nL_m6A5cQX8_XoBV04XE5zcfWqfQijInlZu8Y/edit?gid=0#gid=0)

![Image](https://github.com/user-attachments/assets/a94c56cb-984f-4fe1-aa82-71d83ad4aeb5)

**Comment by psykkis** [comment]
[Dailytask Jatko ohjeistus.pdf](https://github.com/user-attachments/files/18212299/Dailytask.Jatko.ohjeistus.pdf)

**Comment by srbackman** [comment]
_Kysymyksiä/Muutos ehdotuksia_:
- DailyTask prefabien erinäisyys -> tekee DailyTaskMAIN prefabin josta tekee lapset (daily, weekly ja monthly) tai on vain yksi prefabi malli jota muokataan instantiotumisen jälkeen muun datan laiton yhteydessä (väri).
- DailyTaskView prefabin tabline -> oliko suunniteltu nykyiseen muutoksia? Jos ei onko "Oma" ja "Muut" tabit koskaan tulossa käyttöön?
- Branch:in nimeäminen -> UI/Feature/DailyTask/?
- DailyQuest.cs GetQuestData() -> olisiko parempi lähettää isoja data määriä pakattuna luokka:na tai struct:ina vai jättääkö pitkäksi?
- DailyTaskManager.cs -> Muutamat "yield return" kohdat ovat vähän epäselviä.

**Comment by BillTheBeast** [comment]
- Tarkoitat siis niitä tehtävä lappuja mikäli ymmärrän oikein? Sanoisin, että riippuu siitä mikä itsestään tuntuu hyvältä (esim. haluaako leikkiä sen värin vaihtamisen kanssa) Koska ainakin tällä hetkellä niiden erot ainakin visuaalisesti ovat vain se väri, jos niihin halutaan/tulee enemmän eroja ulkonäön kannalta niin silloin erilliset prefabit voisivat olla ihan fiksu idea. @psykkis Halutaanko että ne laput näyttävät erilaiselta kuin vain värin kannalta riippuen tyypistä.
- Oma on periaatteessa tarkoitus olla oma valittu tehtävä ja muut on muiden klaanissa olevien valitut tehtävät. Nää varmaankin voidaan toteuttaa eri tavalla myös kuin asettamalla ne sinne nauhaan, voidaan keskustella tästä hieman enemmän palaverissa.
- UI/DailyTask/Feature/*muutoksen nimi* Muutin hieman mieltäni tuon rakenteen kannalta tossa aikasemmin.
- Tässä tapauksessa voisi helposti vain antaa sen koko PlayerTask objektin. Mutta riippuu omasta mielestäni siitä että haluatko mahdollistaa sen että voit vain antaa ne arvot sille ja että onko järkeä lähteä pakkaamaan tietoja erilliseen objektiin, jos sitä ei käytetä muualla. Olen kylläkin viime aikoina poistanut noita erillisten parametrejen antamista kun on mahdollista antaa koko objekti.
- Rivillä 62 aloitetaan Coroutiini, jolla haetaan tehtävät palvelimelta, jos niitä ei vielä ole haettuna ja sitten jäädään rivillä 72 odottamaan, että nämä tehtävät saapuvat paikalle. Siihen pitäisi varmaankin lisätä return siihen elsen sisään, jos tehtäviä ei voida saada.
   - Rivillä 134 on kyseessä yield ketju, jonka päälimmäisenä tarkoituksena on odottaa, että pelaaja antaa tiedot siitä mitä hän haluaa popupissa tehdä.

**Comment by BillTheBeast** [comment]
Lisään tähän nuo asiat mistä juuri puhuttiin.

- Siivoa hieman ylimääräistä toistoa pois DailyTaskManagerista.
- Korvaa ne tämänhetkiset public muuttujat privaateilla SerializeFieldeillä.
- Siirrä se tehtäväpalkinto palkki osaksi tabinauhaa tai heti sen nauhan alle (eli Contentin yläreunaan). Todennäköisesti osaksi tabinauhaa on siistimpi toteutus.
- Korjaa "valittu tehtävä" ruudun ankkurointi ja skaalaus.
- Lisää Handler-skripti, jolla tehtävän tiedot asetetaan valitun tehtävän ruutuun.
- Lisää tabinauhan nappuloiden listenerit DailyTaskManager skriptin sisältä.
   - Lisää mahdollisuus palata takaisin valittuun tehtävään painamalla Oma Task painiketta tabinauhassa.

**Comment by srbackman** [comment]
DailyTask scriptejä on nyt siivottu.

**Työlista**:
- [ ] Omatyö:n elementtien ankkurointi ja skaalaus korjaus.
- [ ] UI:hin uusittu välilehti kokoonpano ja "ClanReward" palkin siirtäminen.
- [ ] DailyTaskPrefab korteille Main prefab ylläpidon parantamiseksi.
- [ ] DailyTask koodien uusimista uutta välilehti kokoonpanoavarten.
- [ ] DailyTask koodien muokkaamista ja uuden handler scriptin lisäys "omatyö" sivua varten.

**Comment by srbackman** [comment]
-Omatyö sivun skaalauksen ja ankkuroinnin korjailu on valmis. Siinä tuli vietettyä aika paljon aikaa kun yritti saada ne suurinpiirtein näyttämään samalta eri näytöillä.
-DailyTask kortit periytyy nyt yhdestä pää prefab:istä (Prefab -> variant prefab). Pitää vielä korjailla niitten nimi formaatteja oikeaksi kun tuli laitettua väärät aikaisemmin.

**Comment by srbackman** [comment]
-Aamulla tuli korjattua muutamat tiedostojen nimeämiset DailyTask prefab kansiosta.
-Tuli työstettyä DailyTaskManager.cs tiedostoa siihen kuntoon että se ehkä pystyy vaihtamaan eri DailyTask sivujen välillä (saatan joutua palaamaan takas jos siinä on jotain bugeja).
-Kyselin myös DailyTask korttien ulkonäkö varianteista teknisessä mielessä mutta siitä tuli sitten samantien graffinen keskustelu.

**Comment by psykkis** [comment]
@halme1 laittaa unityyn grafiikkakansion common kansioon semmoisen yleisen laatikon niin käytetään sitä nyt alustavasti niissä tehtävissä - osaatko Jonne sanoa koska se ois siellä?

**Comment by psykkis** [comment]
@Katriina36 katotko että ne muut elementit mitä käytetään dailytaskissa kans noudattaa sitä tyylilajia kirkkaudellaan ja värimaailmaltaan. Muotohan toimii kyllä jo

**Comment by srbackman** [comment]
- Tein uuden tab bar layoutin DailyTaskView prefab:iin ja korjailin sitä varten DailyTaskManager.cs tiedostoa.
- Siirsin clan rewards palkin siihen uuden tab bar:in alle ja säädin pisteytys kategorioiden skaalauksia hyödyntämään uutta horisontaalista tilaa DailyTaskView prefab:issä.
- Joku Unityn bugi tuli myös vastaan missä kun on HorizontalLayoutGroup johon isntansioidaan pelin aikana gameobject:it niin HorizontalLayoutGroup:in spacing arvo ei astu voimaan ellei erikseen vielä kutsu `LayoutRebuilder.ForceRebuildLayoutImmediate()` funktiota.

**Comment by srbackman** [comment]
- Pisteytyksen mukaan tulee DT kortti prefab variantit (500, 1000 ja 1500).
- Omatyö sivu täydennetty.
- Omatyö sivun koodin työstö aloitettu.

**Comment by srbackman** [comment]
- Omatyö sivun koodin työstöä jatkettu.
- Aamu palaverissa käytiin läpi uusia töitä.

**Comment by srbackman** [comment]
- DailyTask tehtävät sivun swipaus korjailuja.
- DailyTask omatyö sivun tehtävän peruutus, uudelleen valinta ja testaus toimintojen teko aloitettu.

**Comment by srbackman** [comment]
**TODO:**
- [ ] PlayerTask id PlayerData:an ja sieltä haku.
- [ ] Pelin avautuessa aseta OmaTyö:hön nykyinen tehtävä.
- [ ] Aina olemassa oleva TaskChecker scripti joka tietää ja tarkistaa nykyiset task:in ja tallentaa edistymisen.
- [ ] Kun serveri kunnossa hae ja tallenna DailyTask tietoja serveriin.

**Comment by srbackman** [comment]
- Työstänyt DailyTask klaani sivun rakennetta.

**Comment by srbackman** [comment]
- DailyTask klaani sivun ensimmäinen vedos valmis.
- DailyTask klaani edistymis palkin työ alkanut.

**Comment by srbackman** [comment]
- DailyTask klaanin edistymis palkki testus valmis.

**Comment by srbackman** [comment]
- DailyTask id haetaan ja tallennetaan PlayerData luokkaan.
- Pelin käynnistyksen yhteydessä asetettava omatyö:n haku työn alla.

**Comment by srbackman** [comment]
- Pelin käynnistyksen yhteydessä asetettava omatyö:n haku valmis eilen.
- DailyTaskProgressManager scriptin teko aloitettu.

**Comment by srbackman** [comment]
- DailyTaskProgressManager scriptin teko melkein valmis testausta varten.

**Comment by srbackman** [comment]
- Tehtävät sivun uudistelua ja sen koodi puolen pieniä muutoksia.

**Comment by srbackman** [comment]
- Tehtävät sivun uudistelua ja koodi puolen muutoksia ja lisäyksiä.

**Comment by srbackman** [comment]
- DailyTask edistymis popup on osittain valmis.

**Comment by srbackman** [comment]
- DailyTask edistymis popup on valmis.

**Comment by srbackman** [comment]
- Lisäsin mieliala animaatiot omatyö sivulle.
- Tein klaani palkinto nauhalle erikseen avautuvan popup ikkunan joka ei tällä hetkellä näytä muuta kuin saman kuvan ja randomisoidun numero määrän.
- +Tein Popup.cs pohjalle FadeIn ja FadeOut toiminnon.

**Comment by srbackman** [comment]
- [ ] Hae klaani datasta pelaajat daily task klaani sivulle ja paranna ulkonäköä.
- [ ] Popup joka näyttää saadun palkinnon kun klaanin milestone palkinto saavutetaan.
- [ ] DailyTask scriptien siivoilua.

**Comment by srbackman** [comment]
- Klaanin milestone popup on PR valmis heti kun olen testannut sitä.

**Comment by srbackman** [comment]
- DailyTask:in koodien siivoilua ja dokumentointia.

**Comment by srbackman** [comment]
- Tein DailyTask sivun tab napeille scriptin mikä hoitaa sen että painettu nappi jää alas ja nousee ylös kun jotain toista tab nappia painetaan.

**Comment by srbackman** [comment]
- Klaanin edistymis palkin palkinto popup pystyy nyt tulemaan heti tehtävä edistymis ilmoituksen jälkeen.
- Avatarin mielentila pystyy nyt muuttumaan tehtyjen tehtävien mukaan.

**Comment by srbackman** [comment]
- Tein tehtävien koulutus versiota. Jostain syystä pelin aikana luodut normaalit tehtävä kortit eivät enää osaa asettua oikein.

**Comment by srbackman** [comment]
- Tein tehtävien koulutus version ensimmäisen version valmiiksi.

**Comment by srbackman** [comment]
- [ ] Bugi korjaus: Tehtävän valinta ei aseta tehtävää kokonaan.
- [ ] Pitkä painallus tehtävä toiminto.

**Comment by srbackman** [comment]
- Korjasin yhden bugin liittyen siihen että kun valitsi tehtävän se ei asettunu kokonaan ja sitä ei voinut suorittaa.
- Yritin pitkä painallus tehtävän yhteydessä saada inspectoriin valinnan mukaan näkyviin elementtejä, mutta en onnistunut.

**Comment by srbackman** [comment]
- Aloitin parannetun scrollauksen tekemisen.

**Comment by srbackman** [comment]
- Jatkoin parannetun scrollauksen tekemistä.

**Comment by srbackman** [comment]
- Korjailin parannetun scrollauksen scriptejä.

**Comment by srbackman** [comment]
- Tein valmiiksi parannetun scrollauksen (custom editorin lisäys joskus tulevaisuudessa).

**Comment by srbackman** [comment]
- Tein ominaisuuden että kun avatarin on muokannu ja tallentanu niin se päivittyy muuallekkin (yläpakkiin ja hahmoon).
- Tein niin että tehtävissä näkyy sitä tehtävää vastaava kuva joka näkyy tehtävät sivulla, hyväksymis popupissa ja OmaTyö sivulla.
